#!/usr/bin/env bash
# MIT License
#
# Copyright (c) 2022 gentoo-btw
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# colors
BLK='\e[0;30m'
RED='\e[0;31m'
GRN='\e[2;32m'
YEL='\e[0;33m'
BLU='\e[0;34m'
PURP='\e[0;35m'
CYN='\e[0;36m'
WHT='\e[0;37m'

# hostname, user and other stuff
host_user="$(echo -e ${GRN}$USER${WHT}@${YEL}$HOSTNAME${WHT})"
memtotal="$(cat /proc/meminfo | head -n1 | awk '{print $2}') kB"
memfree="$(cat /proc/meminfo | grep MemFree | awk '{print $2}') kB"
memavailable="$(cat /proc/meminfo | grep MemAvailable | awk '{print $2}') kB"
buffers="$(cat /proc/meminfo | grep Buffers | awk '{print $2}') kB"
cached="$(cat /proc/meminfo | grep Cached | head -n1 | awk '{print $2}') kB"
swaptotal="$(cat /proc/meminfo | grep SwapTotal | awk '{print $2}') kB"
swapfree="$(cat /proc/meminfo | grep SwapFree | awk '{print $2}') kB"
zswap="$(cat /proc/meminfo | grep Zswap | head -n1 | awk '{print $2}') kB"
zswapped="$(cat /proc/meminfo | grep Zswapped | head -n1 | awk '{print $2}') kB"
swapcached="$(cat /proc/meminfo | grep SwapCached | awk '{print $2}') kB"
dirty="$(cat /proc/meminfo | grep Dirty | awk '{print $2}') kB"
colorblocks="$(echo -e ${WHITE}██${RED}██${GRN}██${BLU}██${YEL}██${PURP}██${CYN}██${BLK}██${WHT})"
kernel_stack="$(cat /proc/meminfo | grep KernelStack | awk '{print $2}') kB"
per_cpu="$(cat /proc/meminfo | grep Percpu | awk '{print $2}') kB"

# for ascii logo
yellowpart="$(echo -e ${YEL})"
greenpart="$(echo -e ${GRN})"
blackpart="$(echo -e ${BLK})"
whitepart="$(echo -e ${WHT})"
# output
cat <<EOF

$greenpart   ████████████████████████████     $host_user
$greenpart ████████████████████████████████ $whitepart   -------------
$greenpart ████      ████      ███      ███ $whitepart  RAM Total: $memtotal
$greenpart ████      ████      ███      ███ $whitepart  RAM Free: $memfree
$greenpart ████      ████      ███      ███ $whitepart  RAM Available: $memavailable
$greenpart ████      ████      ███      ███ $whitepart  Buffers: $buffers
$greenpart ████████████████████████████████$whitepart   Cached: $cached
$greenpart ███   ████   █████   █████   ███$whitepart   Swap Total: $swaptotal
$yellowpart ███   ████   █████   █████   ███$whitepart   Swap Free: $swapfree
                                    Zswap: $zswap
                                    Zswapped: $zswapped
                                    Swap Cached: $swapcached
                                    Dirty: $dirty
                                    Kernel Stack: $kernel_stack
                                    Per CPU: $per_cpu

                                    $colorblocks

EOF
