#!/usr/bin/env bash
# MIT License
#
# Copyright (c) 2022 gentoo-btw
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# colors
BLK='\e[0;30m'
RED='\e[0;31m'
GRN='\e[2;32m'
YEL='\e[0;33m'
BLU='\e[0;34m'
PURP='\e[0;35m'
CYN='\e[0;36m'
WHT='\e[0;37m'

while read -r; do
    case "${REPLY}" in
        (MemTotal:*)        memtotal="${REPLY//[^0-9]/} kB" ;;
        (MemFree:*)         memfree="${REPLY//[^0-9]/} kB" ;;
        (MemAvailable:*)    memavailable="${REPLY//[^0-9]/} kB" ;;
        (Buffers:*)         buffers="${REPLY//[^0-9]/} kB" ;;
        (Cached:*)          cached="${REPLY//[^0-9]/} kB" ;;
        (SwapTotal:*)       swaptotal="${REPLY//[^0-9]/} kB" ;;
        (SwapFree:*)        swapfree="${REPLY//[^0-9]/} kB" ;;
        (Zswap:*)           zswap="${REPLY//[^0-9]/} kB" ;;
        (Zswapped:*)        zswapped="${REPLY//[^0-9]/} kB" ;;
        (SwapCached:*)      swapcached="${REPLY//[^0-9]/} kB" ;;
        (Dirty:*)           dirty="${REPLY//[^0-9]/} kB" ;;
        (KernelStack:*)     kernel_stack="${REPLY//[^0-9]/} kB" ;;
        (Percpu:*)          per_cpu="${REPLY//[^0-9]/} kB" ;;
    esac
done < /proc/meminfo

# colorblocks/hostme
host_user="$(printf ${GRN}$USER${WHT}@${YEL}$HOSTNAME${WHT})"
colorblocks="$(printf ${WHITE}██${RED}██${GRN}██${BLU}██${YEL}██${PURP}██${CYN}██${BLK}██${WHT})"
# for ascii logo
yellowpart="$(printf ${YEL})"
greenpart="$(printf ${GRN})"
end="$(printf ${WHT})"
# output
cat <<EOF

$greenpart   ████████████████████████████     $host_user
$greenpart ████████████████████████████████ $end   -------------
$greenpart ████      ████      ███      ███ $end  RAM Total: ${memtotal:-null}
$greenpart ████      ████      ███      ███ $end  RAM Free: ${memfree:-null}
$greenpart ████      ████      ███      ███ $end  RAM Available: ${memavailable:-null}
$greenpart ████      ████      ███      ███ $end  Buffers: ${buffers:-null}
$greenpart ████████████████████████████████$end   Cached: ${cached:-null}
$greenpart ███   ████   █████   █████   ███$end   Swap Total: ${swaptotal:-null}
$yellowpart ███   ████   █████   █████   ███$end   Swap Free: ${swapfree:-null}
                                    Zswap: ${zswap:-null}
                                    Zswapped: ${zswapped:-null}
                                    Swap Cached: ${swapcached:-null}
                                    Dirty: ${dirty:-null}
                                    Kernel Stack: ${kernel_stack:-null}
                                    Per CPU: ${per_cpu:-null}

                                    $colorblocks

EOF
