on: [pull_request]
jobs:
  reviewdog_and_shellcheck:
    name: reviewdog / shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Misspell
        uses: reviewdog/action-misspell@v1
      - uses: actions/checkout@v1
      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
